# This isn't quite working.  I  get failures related to the perl packages.  But
# somehow I did build a working environment, so I saved the full package
# details to build.txt.
channels:
  - conda-forge
  - bioconda
  - defaults
  - eumetsat # needed for a few perl packages
dependencies:
  - airr
  # Biopython 1.73 specifically is needed for compatibility with how
  # Bio.Blast.Applications.NcbiblastnCommandline is called in
  # SONAR/annotate/__init__.py
  # For more information see:
  # https://github.com/biopython/biopython/issues/2055
  # https://github.com/biopython/biopython/pull/2071
  - biopython=1.73
  - docopt
  - ete3
  - fuzzywuzzy 
  - gcc_linux-64
  - lapack
  - pandas
  - perl-bioperl
  - perl-file-copy-recursive
  - perl-file-map
  - perl-file-sharedir
  - perl-io-layers
  - perl-inline-c
  - perl-list-util
  - perl-math-combinatorics
  - perl-module-build
  - perl-path-tiny
  - perl-pegex
  - perl-statistics-basic
  - perl-test-file
  - perl-yaml
  - pyqt=4
  - r-docopt
  - r-ggplot2
  - r-mass
  - r-gridbase # is this the right grid?
  # sra-tools is needed to run fastq-dump in the vignette
  - sra-tools
