channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - airr
  # Biopython 1.73 specifically is needed for compatibility with how
  # Bio.Blast.Applications.NcbiblastnCommandline is called in
  # SONAR/annotate/__init__.py
  # For more information see:
  # https://github.com/biopython/biopython/issues/2055
  # https://github.com/biopython/biopython/pull/2071
  - biopython=1.73
  - docopt
  - ete3
  - fuzzywuzzy 
  - pandas
  - perl-bioperl
  - perl-statistics-basic
  - perl-list-util
  - perl-math-combinatorics
  - pyqt=4
  - r-docopt
  - r-ggplot2
  - r-mass
  - r-gridbase # is this the right grid?
  # sra-tools is needed to run fastq-dump in the vignette
  - sra-tools
